### ISSUE TITLE
Port Number Read as String Causes Increment Issue

### ISSUE THREAD

**Issue by Merlinkk** [kalviumcommunity/S59_Anshul_Capstone_Serflow#50]
![image](https://github.com/kalviumcommunity/S59_Anshul_Capstone_Serflow/assets/80953200/33525710-edce-4945-aed1-5c197dd711b4)

**Description:**
When reading the port number from `process.env.PORT`, the value is being treated as a string rather than a number. This causes issues when attempting to increment the port number for the WebSocket server. As a result, the WebSocket server does not start on the expected port.

**Steps to Reproduce:**
1. Set the `PORT` environment variable to a value (e.g., `5000`).
2. Start the server.
3. Observe that the WebSocket server does not start on the incremented port.

**Expected Behavior:**
The WebSocket server should start on the port immediately following the main server port. For example, if the main server is on port `5000`, the WebSocket server should start on port `5001`.

**Actual Behavior:**
The WebSocket server fails to start on the expected port due to the port number being read as a string and not being incremented properly.

**Comment by ananyatewari** [comment]
Hey

I've previously worked on something similar. Do you mind if I start working on this ?

**Comment by Merlinkk** [comment]
Sure. Please provide your email so i can send you the required Environment variables

**Comment by ananyatewari** [comment]
ananyatewari0205@gmail.com

**Comment by Merlinkk** [comment]
> [ananyatewari0205@gmail.com](mailto:ananyatewari0205@gmail.com)

Concerned files have been sent to your email.

**Comment by Merlinkk** [comment]
Reviewed and merged #51
