### ISSUE TITLE
Update ChatEngine UI from "Pretty" to "Advanced"

### ISSUE THREAD

**Issue by Merlinkk** [kalviumcommunity/S59_Anshul_Capstone_Serflow#52]
## Description
We would like to update the UI of our ChatEngine component from the current "Pretty" design to a more "Advanced" design. The goal is to provide users with a richer, more feature-complete chat experience that includes additional functionalities and a modernized interface.

## Current Behavior
- The current UI follows a "Pretty" design.
- Basic chat functionalities are present.
- Limited customization and advanced features.

## Expected Behavior
- Implement a new "Advanced" UI design.
- Enhanced chat functionalities including but not limited to:
  - Improved message handling (editing, deleting).
  - Advanced user controls (muting, blocking).
  - Customizable themes and layouts.
  - Enhanced media sharing capabilities.
  - Real-time updates and notifications.
- Responsive design for better usability on various devices.

## Steps to Reproduce
1. Implement the new UI design as outlined.
2. Ensure all existing functionalities work seamlessly with the new UI.
3. Test across different devices and screen sizes for responsiveness.

## References
- Pretty UI 
![image](https://github.com/kalviumcommunity/S59_Anshul_Capstone_Serflow/assets/80953200/2982c74e-5c47-4f49-aa3c-8a36ad5a4863)
-  Desired "Advanced" UI. 
![image](https://github.com/kalviumcommunity/S59_Anshul_Capstone_Serflow/assets/80953200/ab38d976-0653-4162-a8a3-ff0ffc4b26d6)

**Comment by Abhinandan-4321** [comment]
Hi. Can i work on this issue??

**Comment by Merlinkk** [comment]
Sure. Please provide your email so I can provide you with the environment variables.

**Comment by Abhinandan-4321** [comment]
abhinandan.gupta@kalvium.community
This is my mail ID you can send the enviornment variables here.

**Comment by Merlinkk** [comment]
> [abhinandan.gupta@kalvium.community](mailto:abhinandan.gupta@kalvium.community) This is my mail ID you can send the enviornment variables here.

Concerned files have been sent to your email.

**Comment by Merlinkk** [comment]
PR #53 Reviewed and merged.
