### ISSUE TITLE
Refactoring Authentication Routes for Better Logic Separation

### ISSUE THREAD

**Issue by Merlinkk** [kalviumcommunity/S59_Anshul_Capstone_Serflow#54]
### Description

Currently, the authentication routes in our application handle both endpoint definitions and logic execution within the same file (`authRoutes.js`). This approach makes the file lengthy and harder to maintain. To improve code organization and readability, we should refactor these routes to separate the logic from the endpoint definitions.

### Goals

1. **Separation of Concerns:** Divide the authentication route file into smaller modules or functions where each handles specific logic related to user authentication, password reset, etc.
   
2. **Code Readability:** Enhance the readability of the authentication routes by clearly separating endpoint definitions from business logic implementations.

### Tasks

- **Create Controller Functions:** Move the existing logic from `authRoutes.js` into separate controller functions (`authControllers.js`) for each endpoint.
  
- **Route Definition Cleanup:** Update `authRoutes.js` to only define endpoints and call corresponding controller functions for handling logic.
  
- **Refactor Password Reset Flow:** Separate password reset flow into distinct functions or modules to handle email sending, OTP verification, and password updating separately.

### Expected Outcome

- **Improved Maintainability:** By organizing the code into smaller, focused modules, future updates and bug fixes will be easier and less error-prone.

- **Clear Separation:** Developers will find it easier to understand and modify specific parts of the authentication flow without affecting unrelated code.

**Comment by Swasti008** [comment]
Can I work on this issue?

**Comment by Merlinkk** [comment]
Sure. Please provide your email so I can provide you with the environment variables.

**Comment by Swasti008** [comment]
Sure . (swastimohanty452@gmail.com)

**Comment by Merlinkk** [comment]
> Sure . ([swastimohanty452@gmail.com](mailto:swastimohanty452@gmail.com))

Concerned files have been sent to your email.

**Comment by Swasti008** [comment]
#55 done. please check and merge.

**Comment by Merlinkk** [comment]
Reviewed #55 and merged

**Comment by Merlinkk** [comment]
Thanks @Swasti008 , reviewed #55 and merged.
